Repository della-padula/YappUltraHardPractice, pull requests merged in 2021-09, with the labels that each got.

#58 공지사항앱 북마크 기능 추가
  Sanghee/Practice1/Practice1.xcodeproj/project.pbxproj
  Sanghee/Practice1/Practice1/AppDelegate.swift
  Sanghee/Practice1/Practice1/Cell/FileUrlTableViewCell.swift
  Sanghee/Practice1/Practice1/Cell/NoticeTableViewCell.swift
  Sanghee/Practice1/Practice1/Constants.swift
  Sanghee/Practice1/Practice1/Extensions/UIColor.swift
  Sanghee/Practice1/Practice1/Info.plist
  Sanghee/Practice1/Practice1/Model.xcdatamodeld/Model.xcdatamodel/contents
  Sanghee/Practice1/Practice1/Model/FileUrl.swift
  Sanghee/Practice1/Practice1/Model/Notice.swift
  Sanghee/Practice1/Practice1/PersistentContainer.xcdatamodeld/PersistentContainer.xcdatamodel/contents
  Sanghee/Practice1/Practice1/Utilities/CoreDataManager.swift
  Sanghee/Practice1/Practice1/Utilities/Functions.swift
  Sanghee/Practice1/Practice1/ViewController/BookmarkViewController.swift
  Sanghee/Practice1/Practice1/ViewController/DetailViewController.swift
  Sanghee/Practice1/Practice1/ViewController/ViewController.swift
Labels: iOS, Feature

#72 #66, #69, #70 로그인, 메인, 기록 화면 생성
  UltraProject1/Podfile.lock
  UltraProject1/UltraProject1.xcodeproj/project.pbxproj
  UltraProject1/UltraProject1/AppDelegate.swift
  UltraProject1/UltraProject1/Base.lproj/Main.storyboard
  UltraProject1/UltraProject1/Extensions/UIColor.swift
  UltraProject1/UltraProject1/Info.plist
  UltraProject1/UltraProject1/SceneDelegate.swift
  UltraProject1/UltraProject1/ViewController.swift
  UltraProject1/UltraProject1/ViewControllers/LoginViewController.swift
  UltraProject1/UltraProject1/ViewControllers/MainViewController.swift
  UltraProject1/UltraProject1/ViewControllers/RecordViewController.swift
Labels: iOS, VIew

#71 #67 결과 화면 생성
  UltraProject1/UltraProject1.xcodeproj/project.pbxproj
  UltraProject1/UltraProject1/ViewControllers/ResultViewController.swift
Labels: iOS, VIew

#73 #68 - 게임 화면 생성
  .DS_Store
  Byeongyun/Practice1/Practice1.xcodeproj/xcuserdata/itlearning.xcuserdatad/xcschemes/xcschememanagement.plist
  UltraProject1/Podfile.lock
  UltraProject1/UltraProject1.xcodeproj/project.pbxproj
  UltraProject1/UltraProject1/ViewControllers/GameCollectionViewCell.swift
  UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
  UltraProject1/UltraProject1/ViewControllers/Numbers.swift
Labels: iOS, VIew

#76 #66, #69, #70 로그인, 메인, 기록 화면 생성
  UltraProject1/Podfile.lock
  UltraProject1/UltraProject1.xcodeproj/project.pbxproj
  UltraProject1/UltraProject1/ViewControllers/LoginViewController.swift
  UltraProject1/UltraProject1/ViewControllers/MainViewController.swift
  UltraProject1/UltraProject1/ViewControllers/RecordViewController.swift
  UltraProject1/UltraProject1/ViewControllers/UIColor.swift
Labels: iOS, VIew

#81 #77 - 결과 화면 resizing
  UltraProject1/UltraProject1/ViewControllers/ResultViewController.swift
Labels: iOS, Improve

#93 코어데이터 매니저 구현
  UltraProject1/Podfile.lock
  UltraProject1/UltraProject1.xcodeproj/project.pbxproj
  UltraProject1/UltraProject1/AppDelegate.swift
  UltraProject1/UltraProject1/CoreDataManager.swift
  UltraProject1/UltraProject1/Model.xcdatamodeld/Model.xcdatamodel/contents
  UltraProject1/UltraProject1/Score.swift
Labels: iOS, Feature

#95 코드 수정, 폴더 파일 연결
  UltraProject1/UltraProject1.xcodeproj/project.pbxproj
  UltraProject1/UltraProject1/Cells/GameCollectionViewCell.swift
  UltraProject1/UltraProject1/Extensions/UIColor.swift
  UltraProject1/UltraProject1/Functions/CoreDataManager.swift
  UltraProject1/UltraProject1/Functions/PrintFn.swift
  UltraProject1/UltraProject1/Models/Numbers.swift
  UltraProject1/UltraProject1/Models/Score.swift
Labels: iOS, Feature

#96 카카오 로그인
  UltraProject1/Podfile
  UltraProject1/Podfile.lock
  UltraProject1/UltraProject1.xcodeproj/project.pbxproj
  UltraProject1/UltraProject1/AppDelegate.swift
  UltraProject1/UltraProject1/Functions/CoreDataManager.swift
  UltraProject1/UltraProject1/Functions/KakaoAuthManager.swift
  UltraProject1/UltraProject1/Info.plist
  UltraProject1/UltraProject1/ViewControllers/LoginViewController.swift
  UltraProject1/UltraProject1/ViewControllers/MainViewController.swift
Labels: iOS, Feature

#105 로그인키 숨김
  UltraProject1/UltraProject1/AppDelegate.swift
Labels: iOS, Feature

#102 기록화면과 결과화면
  UltraProject1/UltraProject1.xcodeproj/project.pbxproj
  UltraProject1/UltraProject1/Cells/ScoreTableViewCell.swift
  UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
  UltraProject1/UltraProject1/ViewControllers/RecordViewController.swift
  UltraProject1/UltraProject1/ViewControllers/ResultViewController.swift
Labels: iOS, Feature

#113 화면 네비게이션 구현
  UltraProject1/UltraProject1/AppDelegate.swift
  UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
  UltraProject1/UltraProject1/ViewControllers/MainViewController.swift
  UltraProject1/UltraProject1/ViewControllers/RecordViewController.swift
Labels: iOS, Feature

#121 앱 ui 및 전체 코드 수정 및 추가
  UltraProject1/Podfile.lock
  UltraProject1/UltraProject1/AppDelegate.swift
  UltraProject1/UltraProject1/Cells/GameCollectionViewCell.swift
  UltraProject1/UltraProject1/Cells/ScoreTableViewCell.swift
  UltraProject1/UltraProject1/Extensions/UIColor.swift
  UltraProject1/UltraProject1/Functions/CoreDataManager.swift
  UltraProject1/UltraProject1/Functions/KakaoAuthManager.swift
  UltraProject1/UltraProject1/Functions/TimerManager.swift
  UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
  UltraProject1/UltraProject1/ViewControllers/LoginViewController.swift
  UltraProject1/UltraProject1/ViewControllers/MainViewController.swift
  UltraProject1/UltraProject1/ViewControllers/RecordViewController.swift
  UltraProject1/UltraProject1/ViewControllers/ResultViewController.swift
Labels: iOS, Feature, VIew
